sudo: required
services:
  - docker
before_install:
  - docker build -t tadamczyk/docker-backend -f docker/backend/Dockerfile.dev docker/backend/.
  - docker build -t tadamczyk/docker-frontend -f docker/frontend/Dockerfile.dev docker/frontend/.
script:
  - docker run -e CI=true tadamczyk/docker-frontend npm test