sudo: required
services:
  - docker
before_install:
  - docker build -t tadamczyk/backend -f backend/Dockerfile.dev backend/.
  - docker build -t tadamczyk/frontend -f frontend/Dockerfile.dev frontend/.
script:
  - docker run -e CI=true tadamczyk/frontend npm test