version: "3"
services:
  my-redis:
    image: redis
    container_name: my-redis
  my-postgres:
    image: postgres
    container_name: my-postgres
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
  my-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: my-backend
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - /opt/app/node_modules
      - ./backend:/opt/app
    ports:
      - "4000:4000"
  my-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: my-frontend
    volumes:
      - /opt/app/node_modules
      - ./frontend:/opt/app
    ports:
      - "3000:3000"
    tty: true
  my-nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: my-nginx
    ports:
      - "8080:80"