apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 30009
  selector:
    app: my-backend
    type: backend
